### ISSUE TITLE
无法支持快进，慢进问题，希望暴露速度等属性，增加轨迹的快进，慢进，谢谢

### ISSUE THREAD

**Issue by rondsjinhuajin** [Igor-Vladyka/leaflet.motion#13]
遇到需要增加快进，慢进的问题，没有速度属性，时间duration计算的随机，不准确，很难控制，而且轨迹duration重新计算之后，会往后跑一段距离，影响体验，极力希望暴露速度属性，增加快进，慢进功能

**Comment by Igor-Vladyka** [comment]
Hi, 

Please use last version of plugin and check this part:
https://github.com/Igor-Vladyka/leaflet.motion#lmotionpolyline-and-lmotionpolygon
basically you should be able to use **motionSpeed** to change animation speed.

--------- Google translate:
请使用最新版本的插件并检查以下部分：
https://github.com/Igor-Vladyka/leaflet.motion#lmotionpolyline-and-lmotionpolygon
基本上，您应该可以使用 **motionSpeed** 来更改动画速度。
