### ISSUE TITLE
map is not defined

### ISSUE THREAD

**Issue by Ivan-hl** [Igor-Vladyka/leaflet.motion#14]
hello my brother, i'm sorry my english is not good;
when i use the speed , it will be an error `map is not defined`;
After I read the source code， i think the error is here ⬇️
![image](https://user-images.githubusercontent.com/42164477/88651650-7c104b00-d0fc-11ea-84b3-6bdc42484c36.png)
![image](https://user-images.githubusercontent.com/42164477/88651684-86324980-d0fc-11ea-8e27-40abf664f0c9.png)
![image](https://user-images.githubusercontent.com/42164477/88651714-8cc0c100-d0fc-11ea-9de5-d83d4061ab95.png)
can u help me ?

**Comment by Igor-Vladyka** [comment]
Hello there.

Yes, I missed that case. Thank you! 
Fix applied. Please get version 0.2.3 - it's a fresh one from npm.

Regards,
Igor
