### ISSUE TITLE
Rotating icons

### ISSUE THREAD

**Issue by babsevensix** [Igor-Vladyka/leaflet.motion#18]
Hi, 
your plugin is very wonderful!!!!
It would be better if it can rotate marker on direction of marker.
For example, if you put plane icon, it would be much nicer if it were rotated in the target direction .

**Comment by Igor-Vladyka** [comment]
Hey there,

It was suppose to work, let me check what have happened.

**Comment by Igor-Vladyka** [comment]
Hey @babsevensix. It's working as intended, but it was missing from the doucmentation, please check it out in **marker options** for **motion-base** parameter on icon itself
