### ISSUE TITLE
check Layer type before calling setLatLngs 

### ISSUE THREAD

**Issue by mabi** [Igor-Vladyka/leaflet.motion#20]
Executing the demo I get the following error:
Uncaught TypeError: l.setLatLngs is not a function
here:
https://github.com/Igor-Vladyka/leaflet.motion/blob/77870c8baaf96b67f9c0f70259f73191e752382a/src/layer/leaflet.motion.seq.js#L79
I suggest adding a type check e.g.
`if(l instanceof L.Polyline){
...
}`

**Comment by Igor-Vladyka** [comment]
WIll be fixed in next version very soon, thanks
