### ISSUE TITLE
Don't simplify line before drawing 

### ISSUE THREAD

**Issue by Patabugen** [Igor-Vladyka/leaflet.motion#21]
Hey,

I'm having an issue whereby my Polyline (which has about 13,000 LatLngs, but I have the same issue if I clip it to just the first 200) is simplified during the animaiton - then smoothed out afterwards.

During Motion:
![image](https://user-images.githubusercontent.com/196795/112141176-e1a1d200-8bcc-11eb-97cc-e4e06697e9b5.png)

After Motion:
![image](https://user-images.githubusercontent.com/196795/112141206-ecf4fd80-8bcc-11eb-9215-1ef684e6b070.png)

I've tried setting the [`smoothFactor` and `noClip`](https://leafletjs.com/reference-1.7.1.html#polyline-smoothfactor) options but that doesn't seem to help.

I've been digging through the Motion source code to see if I can find anything which might be causing it, but I think this is more to do with how the Polyline acts when being used by Motion.

Has anyone else had this issue, or have any suggestions for how to change it?

**Comment by Igor-Vladyka** [comment]
Hey,

I have time now to make it work, need some time for refactoring and testing it. It will be release in next major version.

**Comment by Igor-Vladyka** [comment]
Hey @Patabugen . Please check latest version, with improved line rendering.
