### ISSUE TITLE
The NextPoint latlng  is not exist in the path

### ISSUE THREAD

**Issue by Minglu-Huo** [Igor-Vladyka/leaflet.motion#24]
I want to draw a marker when motionStatr, but I see the next point is not exist in my local path；

 The latlng has already been taken care of in the _motion, but I need the source point

**Comment by Igor-Vladyka** [comment]
Hey there, can you please provide detailed example so I can help.

**Comment by Merulast** [comment]
@Ivan-hl you probably forgott an `await` somewhere and your data is not ready.
