### ISSUE TITLE
bind a pop or tooltip to marker

### ISSUE THREAD

**Issue by dolorain** [Igor-Vladyka/leaflet.motion#28]
This plugin solves a lot of my problems, but I don't know how to bind the pop ir tooltip to the marker.
All I can think of is that the pop moves with the marker, could this be a problem?
like this.
![image](https://user-images.githubusercontent.com/17894063/160063359-b187f81b-f4d8-4b6f-ba77-1620e6b4711d.png)

**Comment by dolorain** [comment]
I solved it.

**Comment by chenshuqun** [comment]
how to solve it?

**Comment by chenshuqun** [comment]
> how to solve it?

**Comment by aslanispavlos** [comment]
@chenshuqun 

Probably a bit late of response, but it might also help others.

How I did it was,

```
const motionPolyline = L.motion.polyline(.....).addTo(map);

motionPolyline.getMarker().bindTooltip('Hello World!').openTooltip()
```

**Comment by arrrmo** [comment]
Hi
Thanks for this great plugin !
Sorry if my question is silly, I am not a professional developer (and pretty new to mapping/GIS/etc) 
I have a question that extends this one : with the answer above, I managed to bind a tooltip to the marker with static content but I would like the content of this tooltip to be dynamically updated along the path. 
My path is an aircraft ADS-B track in GeoJson format (can be another format if needed) as a featureCollection of Points with lat/lng/alt coordinates, plus an additional property in each point which is a timestamp.
This is what I am trying to do : on each marker move event, update the tooltip content with the new timestamp.
Would you have an idea how to do this ?
Any help would be greatly appreciated !
