### ISSUE TITLE
Is possible to make a ping pong animation?

### ISSUE THREAD

**Issue by tonijota** [Igor-Vladyka/leaflet.motion#3]
I mean, when the animation reach the end, loop back and not start over again from the begining.

**Comment by Igor-Vladyka** [comment]
Yeah. It's simple: you need to create 2 animations (polygon or polilyne), one to show direct animation and second to show reverted animation (with appropriate configurations).
And then just put them into L.motion.seq().
Then listen to 'L.Motion.Event.Ended' event from seq manager and start it again.

All needed details you can find in README.

If you have any problem - please create an jqbin or so with an example so I can help you.
