### ISSUE TITLE
Method to get marker

### ISSUE THREAD

**Issue by aswinkumar863** [Igor-Vladyka/leaflet.motion#7]
A method like `getMarker` helps to extend the marker functionality such as bind events to the Leaflet.motion's marker

**Current workaround**

```
var motionLine = L.motion.polyline( ... )
var marker = motionLine.__marker
```
**Expected**

```
var motionLine = L.motion.polyline( ... )
var marker = motionLine.getMarker()
```

**Related Stackoverflow questions**

- https://stackoverflow.com/questions/57358979/how-to-add-events-to-marker-by-using-leaflet-motion

- https://stackoverflow.com/questions/57489468/how-can-the-map-be-centered-at-a-moving-marker-after-the-marker-has-been-clicked

**Comment by Igor-Vladyka** [comment]
Hi there,

Thanks for posting it, and answering all questions on stackoverflow :)

Just added getMarker() and getMarkers() logic to all motion components.
+ additonal param showMarker to visualize marker on the map before animation stated.

Please let me know if any,

Regards,
Igor

**Comment by aswinkumar863** [comment]
Thank you @Igor-Vladyka for your support. I will let you know if any :)

**Comment by andrusha19** [comment]
Hi
Now your demo gives an error in getMarker method:
"Uncaught ReferenceError: marker is not defined"

In /dist folder you have this code:
```
getMarker: function () {
    if (this.markerOptions) {
        if (!this.__marker) {
                this.__marker = L.marker([0, 0], this.markerOptions);
                if (this.markerOptions.showMarker) {
                     marker.addTo(this._map);   <<<  Here it should be this.__marker.addTo(this._map);
                 }
        }
    }
    return this.__marker;
}
```

In source code it looks like:
```
getMarker: function () {
	return this.__marker;
}
```

Please correct code in /dist folder
